# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.prompt_api import PromptApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestSettingsPromptApi(unittest.TestCase):
    """SettingsPromptApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.settings_prompt_api.SettingsPromptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_default_prompt_settings(self):
        """Test case for get_default_prompt_settings

        Get Default Prompt Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
