# coding: utf-8

"""
    😸 Cheshire-Cat API

    Open source and customizable AI architecture

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.embedder_api import EmbedderApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestEmbedderApi(unittest.TestCase):
    """EmbedderApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.embedder_api.EmbedderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_embedder_settings(self):
        """Test case for get_embedder_settings

        Get Embedder Settings  # noqa: E501
        """
        pass

    def test_get_embedders_settings(self):
        """Test case for get_embedders_settings

        Get Embedders Settings  # noqa: E501
        """
        pass

    def test_upsert_embedder_setting(self):
        """Test case for upsert_embedder_setting

        Upsert Embedder Setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
