# coding: utf-8

"""
    😸 Cheshire-Cat API

    Open source and customizable AI architecture

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.settings_api import SettingsApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.settings_api.SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_setting(self):
        """Test case for create_setting

        Create Setting  # noqa: E501
        """
        pass

    def test_delete_setting(self):
        """Test case for delete_setting

        Delete Setting  # noqa: E501
        """
        pass

    def test_get_setting(self):
        """Test case for get_setting

        Get Setting  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Get Settings  # noqa: E501
        """
        pass

    def test_update_setting(self):
        """Test case for update_setting

        Update Setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
