# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.status_api import StatusApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_home(self):
        """Test case for home

        Home  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
