# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cheshire_cat_api
from cheshire_cat_api.models.body_upload_url import BodyUploadUrl  # noqa: E501
from cheshire_cat_api.rest import ApiException

class TestBodyUploadUrl(unittest.TestCase):
    """BodyUploadUrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyUploadUrl
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyUploadUrl`
        """
        model = cheshire_cat_api.models.body_upload_url.BodyUploadUrl()  # noqa: E501
        if include_optional :
            return BodyUploadUrl(
                url = '', 
                chunk_size = 56, 
                chunk_overlap = 56, 
                summary = True
            )
        else :
            return BodyUploadUrl(
                url = '',
        )
        """

    def testBodyUploadUrl(self):
        """Test BodyUploadUrl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
