# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.memory_api import MemoryApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestMemoryApi(unittest.TestCase):
    """MemoryApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.memory_api.MemoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_element_in_memory(self):
        """Test case for delete_element_in_memory

        Delete Element In Memory  # noqa: E501
        """
        pass

    def test_get_collections(self):
        """Test case for get_collections

        Get Collections  # noqa: E501
        """
        pass

    def test_recall_memories_from_text(self):
        """Test case for recall_memories_from_text

        Recall Memories From Text  # noqa: E501
        """
        pass

    def test_wipe_collections(self):
        """Test case for wipe_collections

        Wipe Collections  # noqa: E501
        """
        pass

    def test_wipe_conversation_history(self):
        """Test case for wipe_conversation_history

        Wipe Conversation History  # noqa: E501
        """
        pass

    def test_wipe_single_collection(self):
        """Test case for wipe_single_collection

        Wipe Single Collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
