# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.large_language_model_api import LargeLanguageModelApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestSettingsLargeLanguageModelApi(unittest.TestCase):
    """SettingsLargeLanguageModelApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.large_language_model_api.LargeLanguageModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_llm_settings(self):
        """Test case for get_llm_settings

        Get Llm Settings  # noqa: E501
        """
        pass

    def test_upsert_llm_setting(self):
        """Test case for upsert_llm_setting

        Upsert Llm Setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
