# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.plugins_api import PluginsApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestPluginsApi(unittest.TestCase):
    """PluginsApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.plugins_api.PluginsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_plugin(self):
        """Test case for delete_plugin

        Delete Plugin  # noqa: E501
        """
        pass

    def test_get_plugin_details(self):
        """Test case for get_plugin_details

        Get Plugin Details  # noqa: E501
        """
        pass

    def test_get_plugin_settings(self):
        """Test case for get_plugin_settings

        Get Plugin Settings  # noqa: E501
        """
        pass

    def test_install_plugin(self):
        """Test case for install_plugin

        Install Plugin  # noqa: E501
        """
        pass

    def test_list_available_plugins(self):
        """Test case for list_available_plugins

        List Available Plugins  # noqa: E501
        """
        pass

    def test_toggle_plugin(self):
        """Test case for toggle_plugin

        Toggle Plugin  # noqa: E501
        """
        pass

    def test_upsert_plugin_settings(self):
        """Test case for upsert_plugin_settings

        Upsert Plugin Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
