# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import cheshire_cat_api
from cheshire_cat_api.api.rabbit_hole_api import RabbitHoleApi  # noqa: E501
from cheshire_cat_api.rest import ApiException


class TestRabbitHoleApi(unittest.TestCase):
    """RabbitHoleApi unit test stubs"""

    def setUp(self):
        self.api = cheshire_cat_api.api.rabbit_hole_api.RabbitHoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Upload File  # noqa: E501
        """
        pass

    def test_upload_memory(self):
        """Test case for upload_memory

        Upload Memory  # noqa: E501
        """
        pass

    def test_upload_url(self):
        """Test case for upload_url

        Upload Url  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
