# coding: utf-8

"""
    😸 Cheshire-Cat API

    Customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import cheshire_cat_api
from cheshire_cat_api.models.setting_body import SettingBody  # noqa: E501
from cheshire_cat_api.rest import ApiException

class TestSettingBody(unittest.TestCase):
    """SettingBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SettingBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingBody`
        """
        model = cheshire_cat_api.models.setting_body.SettingBody()  # noqa: E501
        if include_optional :
            return SettingBody(
                name = '', 
                value = cheshire_cat_api.models.value.Value(), 
                category = ''
            )
        else :
            return SettingBody(
                name = '',
                value = cheshire_cat_api.models.value.Value(),
        )
        """

    def testSettingBody(self):
        """Test SettingBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
