# coding: utf-8

"""
    😸 Cheshire-Cat API

    Open source and customizable AI architecture  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import cheshire_cat_api
from cheshire_cat_api.model.http_validation_error import HTTPValidationError
from cheshire_cat_api import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
