# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import cheshire_cat_api
from cheshire_cat_api.paths.llm_settings_language_model_name import put  # noqa: E501
from cheshire_cat_api import configuration, schemas, api_client

from .. import ApiTestMixin


class TestLlmSettingsLanguageModelName(ApiTestMixin, unittest.TestCase):
    """
    LlmSettingsLanguageModelName unit test stubs
        Upsert Llm Setting  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = put.ApiForput(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
